Update commit-message-check.yml
check lowercase on commit message

diff --git a/.github/workflows/commit-message-check.yml b/.github/workflows/commit-message-check.yml
--- a/.github/workflows/commit-message-check.yml
+++ b/.github/workflows/commit-message-check.yml
@@ -1,23 +1,25 @@
 name: check commit message lower case
+
 on:
   push: 
     branches: 
-      -main
-      -develop
+      - main
+      - develop
 
 jobs:
   check-commit-message:
-    runs-on: ubuntu:latest
+    runs-on: ubuntu-latest
+    
     steps:
-      -name: checkout repository
-       uses: actions/checkout@v2
+      - name: checkout repository
+        uses: actions/checkout@v2
 
-      -name: check commit message case
-       run: |
-        for commit_msg in 
-        do
-        if [["commit_msg" =~ [A-Z] ]]; then
-          echo "error: commit message should be in lower case"
-          exit 1
-        fi
-        done
+      - name: check commit message case
+        run: |
+          for commit_msg in 
+          do
+          if [["commit_msg" =~ [A-Z] ]]; then
+            echo "error: commit message should be in lower case"
+            exit 1
+          fi
+          done
